# Generated by Django 5.2.6 on 2025-10-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_private',
            new_name='this_recipe_is_private',
        ),
    ]
