# Generated by Django 5.2.6 on 2025-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recipe_description_recipe_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.TextField(),
        ),
    ]
