# Generated by Django 5.2.6 on 2025-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
