# Generated by Django 5.2.6 on 2025-10-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_diet_userdiet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('food_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity_other', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_oz', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.TextField()),
                ('protein_g', models.TextField()),
                ('fat_g', models.TextField()),
                ('carbs_g', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('image', models.TextField()),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
    ]
