# Generated by Django 5.2.6 on 2025-10-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_scrapedingredient_scrapedinventory_scrapednutrition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedNutrition',
            new_name='ScrapedNutritionalInfo',
        ),
    ]
