# Generated by Django 5.2.6 on 2025-10-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_scrapednutrition_scrapednutritionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapednutritionalinfo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
