# Generated by Django 5.2.6 on 2025-10-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_scrapednutritionalinfo_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_instances', to='api.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooked_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cooked_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.DecimalField(decimal_places=4, max_digits=5)),
                ('eaten_at', models.DateTimeField(auto_now_add=True)),
                ('cooked_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.cookedrecipe')),
            ],
            options={
                'ordering': ['-eaten_at'],
            },
        ),
    ]
