# Generated by Django 5.2.6 on 2025-10-27 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cookedrecipe_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_g',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_g',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_g',
            field=models.TextField(default='0'),
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_inventories', to='api.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ingredient__name'],
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
