# Generated by Django 5.2.6 on 2025-10-27 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cookedrecipe_meal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_g',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_g',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_g',
            field=models.TextField(default='0'),
        ),
    ]
