# Generated by Django 5.2.6 on 2025-10-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_favoriterecipe'),
        ('api', '0013_userinventory'),
    ]

    operations = [
    ]
