# Generated by Django 5.2.6 on 2025-10-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ingredient_calories_ingredient_carbs_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='food_category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_other',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
