# Generated by Django 5.2.6 on 2025-10-30 14:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_0013_favoriterecipe_0013_userinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='portion',
        ),
        migrations.AddField(
            model_name='cookedrecipe',
            name='total_servings_cooked',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='meal',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_servings',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=6),
        ),
    ]
