# Generated by Django 5.2.6 on 2025-10-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ingredient_food_category_ingredient_price_and_more'),
        ('api', '0016_remove_recipe_total_servings_and_more'),
    ]

    operations = [
    ]
