# Generated by Django 5.2.6 on 2025-11-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_healthdetails_onboardingsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetails',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthdetails',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthdetails',
            name='height_ft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthdetails',
            name='height_in',
            field=models.IntegerField(default=0),
        ),
    ]
