# Generated by Django 5.2.6 on 2025-11-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_healthdetails_weight_alter_healthdetails_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdetails',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
