# Generated by Django 5.2.6 on 2025-11-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_recipetag_alter_taggedrecipe_tag_userrecipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='taggedrecipe',
            name='user',
        ),
    ]
