# Generated by Django 5.2.6 on 2025-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tool_calls',
            field=models.JSONField(blank=True, help_text='Tool calls made by the assistant (name, parameters, results, timestamp)', null=True),
        ),
    ]
