# Generated by Django 5.2.6 on 2025-11-11 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_chatmessage_tool_calls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbs_g_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('search_terms', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curated_ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CuratedIngredientCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='LLM confidence in this mapping (0.0-1.0)')),
                ('is_primary', models.BooleanField(default=False, help_text='Best representative of the curated ingredient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_mappings', to='api.ingredient')),
                ('curated_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_mappings', to='api.curatedingredient')),
            ],
            options={
                'ordering': ['-confidence_score', 'canonical_ingredient__name'],
                'unique_together': {('curated_ingredient', 'canonical_ingredient')},
            },
        ),
        migrations.CreateModel(
            name='RecipeCuratedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text="Human-readable quantity (e.g., '2 cups', '1 lb')", max_length=50)),
                ('raw_ingredient_text', models.TextField(help_text='Original ingredient text from recipe for reference')),
                ('matched_confidence', models.FloatField(default=0.0, help_text='Confidence score for the ingredient match (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curated_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='api.curatedingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_ingredients', to='api.recipe')),
            ],
            options={
                'ordering': ['recipe', 'curated_ingredient__name'],
                'unique_together': {('recipe', 'curated_ingredient', 'raw_ingredient_text')},
            },
        ),
    ]
