# Generated by Django 5.2.6 on 2025-11-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_curatedingredient_curatedingredientcluster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedingredient',
            name='calories_per_100g',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='carbs_g_per_100g',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='fat_g_per_100g',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='protein_g_per_100g',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='search_terms',
        ),
        migrations.RemoveField(
            model_name='curatedingredient',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='recipecuratedingredient',
            unique_together={('recipe', 'curated_ingredient')},
        ),
        migrations.DeleteModel(
            name='CuratedIngredientCluster',
        ),
        migrations.RemoveField(
            model_name='recipecuratedingredient',
            name='matched_confidence',
        ),
        migrations.RemoveField(
            model_name='recipecuratedingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='recipecuratedingredient',
            name='raw_ingredient_text',
        ),
    ]
