# Generated by Django 5.2.6 on 2025-11-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_curatedingredient_calories_per_100g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCuratedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curated_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_curated_inventories', to='api.curatedingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['curated_ingredient__name'],
                'unique_together': {('user', 'curated_ingredient')},
            },
        ),
    ]
