# Generated by Django 5.2.6 on 2025-11-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_usercuratedinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curatedingredient',
            options={'ordering': ['-frequency', 'name']},
        ),
        migrations.AddField(
            model_name='curatedingredient',
            name='frequency',
            field=models.IntegerField(db_index=True, default=0, help_text='Number of recipes using this ingredient'),
        ),
        migrations.AddField(
            model_name='curatedingredient',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of recipes using this ingredient', max_digits=5),
        ),
    ]
