# Generated by Django 5.2.6 on 2025-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_recipe_deliciousness_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='deliciousness_notes',
            field=models.TextField(blank=True, default='', help_text='LLM justification for deliciousness score (5-25 words)'),
        ),
    ]
