# Generated by Django 5.2.6 on 2025-11-16 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_recipe_deliciousness_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeBreakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans_br', to='api.recipe')),
                ('recipeDinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans_dr', to='api.recipe')),
                ('recipeLunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans_lu', to='api.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='TestIncompleteMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_meal_plans', to=settings.AUTH_USER_MODEL)),
                ('mealPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_meal_plans', to='api.testmealplan')),
            ],
            options={
                'unique_together': {('user', 'mealPlan')},
            },
        ),
    ]
