# Generated by Django 5.2.6 on 2025-11-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_recipe_deliciousness_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='channel',
            field=models.CharField(choices=[('nutritionist', 'Nutritionist'), ('souschef', 'SousChef')], db_index=True, default='nutritionist', max_length=32),
        ),
    ]
