# Generated by Django 5.2.6 on 2025-11-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_mealplan_mealplanentry'),
        ('api', '0032_recipe_deliciousness_notes'),
    ]

    operations = [
    ]
