# Generated by Django 5.2.6 on 2025-11-17 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_merge_20251116_1333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InProgressRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='', help_text='Pipe-separated instruction steps')),
                ('prep_time_min', models.IntegerField(default=0)),
                ('cook_time_min', models.IntegerField(default=0)),
                ('total_time_min', models.IntegerField(default=0)),
                ('servings', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_confirmation', 'Pending Confirmation'), ('discarded', 'Discarded')], default='draft', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_progress_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InProgressRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curated_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_progress_recipe_uses', to='api.curatedingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.inprogressrecipe')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inprogressrecipe',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'discarded'), _negated=True), fields=('user',), name='unique_active_recipe_per_user'),
        ),
    ]
