# Generated by Django 5.2.6 on 2025-11-17 20:18

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.search import SearchVector
import django.contrib.postgres.search


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_inprogressrecipe_inprogressrecipeingredient_and_more'),
    ]

    operations = [
        # Step 1: Add the search_vector field (nullable initially)
        migrations.AddField(
            model_name='recipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),

        # Step 2: Populate search_vector for existing recipes using SQL
        migrations.RunSQL(
            sql="""
                UPDATE api_recipe SET search_vector = (
                    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(ingredients, '')), 'B') ||
                    setweight(to_tsvector('english', coalesce(instructions, '')), 'C')
                );
            """,
            reverse_sql="UPDATE api_recipe SET search_vector = NULL;"
        ),

        # Step 3: Create GIN index for fast full-text search
        migrations.RunSQL(
            sql="CREATE INDEX api_recipe_search_vector_idx ON api_recipe USING GIN (search_vector);",
            reverse_sql="DROP INDEX IF EXISTS api_recipe_search_vector_idx;"
        ),

        # Step 4: Create trigger function to auto-update search_vector on INSERT/UPDATE
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION api_recipe_search_vector_trigger() RETURNS trigger AS $$
                BEGIN
                    NEW.search_vector :=
                        setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
                        setweight(to_tsvector('english', coalesce(NEW.ingredients, '')), 'B') ||
                        setweight(to_tsvector('english', coalesce(NEW.instructions, '')), 'C');
                    RETURN NEW;
                END
                $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS api_recipe_search_vector_trigger();"
        ),

        # Step 5: Attach trigger to Recipe table
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER api_recipe_search_vector_update
                BEFORE INSERT OR UPDATE ON api_recipe
                FOR EACH ROW EXECUTE FUNCTION api_recipe_search_vector_trigger();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS api_recipe_search_vector_update ON api_recipe;"
        ),
    ]
