# Generated by Django 5.2.6 on 2025-11-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_chatconversation_channel'),
        ('api', '0034_inprogressrecipe_inprogressrecipeingredient_and_more'),
    ]

    operations = [
    ]
