# Generated by Django 5.2.6 on 2025-11-18 15:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20251117_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplanentry',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=6),
        ),
    ]
