# Generated by Django 5.2.6 on 2025-11-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_recipe_full_text_search'),
        ('api', '0036_mealplanentry_servings'),
    ]

    operations = [
    ]
