# Generated by Django 5.2.6 on 2025-11-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_merge_20251118_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='turkey_notes',
            field=models.TextField(blank=True, default='', help_text='LLM justification for turkey score (5-25 words)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='turkey_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='LLM-assessed turkey score from 0-100', max_digits=5),
        ),
    ]
