# Generated by Django 5.2.6 on 2025-11-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_testmealplan_testincompletemealplan'),
        ('api', '0037_merge_20251118_1041'),
    ]

    operations = [
    ]
