# Generated by Django 5.2.6 on 2025-11-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_recipe_turkey_notes_recipe_turkey_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingsession',
            name='current_step_index',
            field=models.IntegerField(default=0, help_text='Index of the current recipe step (0-based)'),
        ),
    ]
