# Generated by Django 5.2.6 on 2025-11-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20251118_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmealplan',
            name='recipeBreakfast',
        ),
        migrations.RemoveField(
            model_name='testmealplan',
            name='recipeDinner',
        ),
        migrations.RemoveField(
            model_name='testmealplan',
            name='recipeLunch',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='ai_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TestIncompleteMealPlan',
        ),
        migrations.DeleteModel(
            name='TestMealPlan',
        ),
    ]
