# Generated by Django 5.2.6 on 2025-11-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_testmealplan_recipebreakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='week_start',
            field=models.DateField(blank=True, help_text='Monday at beginning of meal plan week', null=True),
        ),
    ]
