# Generated by Django 5.2.6 on 2025-11-23 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_mealplan_week_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='week_start',
            field=models.DateField(default=datetime.datetime(2025, 11, 23, 6, 0, 38, 520399), help_text='Monday at beginning of meal plan week'),
        ),
    ]
