# Generated by Django 5.2.6 on 2025-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_mealplan_week_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='week_start',
            field=models.DateField(help_text='Monday at beginning of meal plan week'),
        ),
    ]
