# Generated by Django 5.2.6 on 2025-12-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_cookingsession_current_step_index'),
        ('api', '0043_alter_mealplan_week_start'),
    ]

    operations = [
    ]
