# Generated by Django 5.2.6 on 2025-12-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_merge_20251201_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRestrictedCuratedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_ingredients', to='api.diet')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_diets', to='api.curatedingredient')),
            ],
            options={
                'ordering': ['ingredient__name'],
                'unique_together': {('diet', 'ingredient')},
            },
        ),
    ]
