"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from os import environ as env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = env.get("DJANGO_DEBUG", "False") == "True"

# email forwarding setup

EMAIL_HOST = 'smtp4dev'
EMAIL_PORT = 25

CRONJOBS = [
  # weekly
  # ('0 6 * * 0', 'weekly_emails'),
  ('*/5 * * * #', 'weekly_emails'),
  ('*/5 * * * #', 'weekly_grocery_emails'),
  # daily
  ('0 6 * * *', 'daily_emails')
  
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Application definition

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.get("DJANGO_DB_NAME", "api"),
        "USER": env.get("DJANGO_DB_USER", "dbuser"),
        "PASSWORD": env.get("DJANGO_DB_PASSWORD", "dbpass"),
        "HOST": env.get("DJANGO_DB_HOST", "0.0.0.0"),
        "PORT": env.get("DJANGO_DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = env.get("DJANGO_STATIC_URL", 'static/')
MEDIA_URL = env.get("DJANGO_MEDIA_URL", 'media/')
STATIC_ROOT = env.get("DJANGO_STATIC_ROOT", '/var/www/static/')
MEDIA_ROOT = env.get("DJANGO_MEDIA_ROOT", '/var/www/media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

REST_FRAMEWORK = {
'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication'],
'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Sous Chef API',
    'DESCRIPTION': 'REST API for Sous Chef application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# DEVELOPMENT environment
if DEBUG == True:
    SECRET_KEY = 'django-insecure-g5kt_ez1(+i$ru&a0*)wamwgvcp^6&t-&zb#^@#+*h2j-@0%z+'

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    ALLOWED_HOSTS = ['*']

    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:5173",  # Vite default
    ]
    CORS_ALLOW_CREDENTIALS = True  # Required for session cookies

    # Session configuration for cross-origin requests
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_HTTPONLY = True  # Protect against XSS
    SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

    # CSRF configuration for SPA
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
    CSRF_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:8000"
    ]

# PRODUCTION environment
# (https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/)
else:
    SECRET_KEY = env.get("DJANGO_SECRET_KEY")
    ALLOWED_HOSTS = ['www.souschef.life', 'souschef.life']
    CORS_ALLOWED_ORIGINS = [
        "http://www.souschef.life",
        "http://souschef.life",  # Vite default
    ]
    CORS_ALLOW_CREDENTIALS = True  # Required for session cookies

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }

    # Session configuration for cross-origin requests
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_HTTPONLY = True  # Protect against XSS
    SESSION_COOKIE_SECURE = True  # Set to True in production with HTTPS

    # CSRF configuration for SPA
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token
    CSRF_COOKIE_SECURE = True  # Set to True in production with HTTPS
    CSRF_TRUSTED_ORIGINS = [
        "http://souschef.life",
        "http://www.souschef.life"
        "https://souschef.life",
        "https://www.souschef.life"
    ]

    # https://docs.djangoproject.com/en/5.2/ref/databases/#persistent-database-connections
    CONN_MAX_AGE = 60
    CONN_HEALTH_CHECKS = True
