[ec2]
sous-chef-prod ansible_host=54.226.217.180

[ec2:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/connor-keypair.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o ForwardAgent=yes -o IdentityAgent=~/.1password/agent.sock
